In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.18.2


# Creating an Array

In [3]:
#Scalar
a = np.array(10)
a

array(10)

In [5]:
type(a)

numpy.ndarray

In [4]:
print(a.size)
print(a.ndim)
print(a.dtype)
print(a.shape)

1
0
int32
()


In [7]:
#Vector
b = np.array([1,2,3])
print(b)
print(b.size)
print(b.ndim)
print(b.dtype)
print(b.shape)

[1 2 3]
3
1
int32
(3,)


In [8]:
#Matrix
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.size)
print(c.ndim)
print(c.dtype)
print(c.shape)

[[1 2 3]
 [4 5 6]]
6
2
int32
(2, 3)


In [14]:
d = np.random.randint(0,10,10)
d

array([8, 2, 7, 1, 0, 7, 0, 3, 7, 9])

In [15]:
d.reshape(2,5)

array([[8, 2, 7, 1, 0],
       [7, 0, 3, 7, 9]])

In [17]:
d.reshape(2,5).astype('float32')

array([[8., 2., 7., 1., 0.],
       [7., 0., 3., 7., 9.]], dtype=float32)

In [19]:
d.sort()
d

array([0, 0, 1, 2, 3, 7, 7, 7, 8, 9])

In [20]:
d = np.unique(d)
d

array([0, 1, 2, 3, 7, 8, 9])

In [21]:
np.append(d,6)

array([0, 1, 2, 3, 7, 8, 9, 6])

In [22]:
np.power(d,2)

array([ 0,  1,  4,  9, 49, 64, 81], dtype=int32)

In [23]:
np.power(d,d)

array([        1,         1,         4,        27,    823543,  16777216,
       387420489], dtype=int32)

In [24]:
np.sqrt(d)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.64575131,
       2.82842712, 3.        ])

In [26]:
x = np.ones([10])
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
x.size

10

In [66]:
y = np.zeros([10],dtype = int)
print(y)
print(y.dtype)

[0 0 0 0 0 0 0 0 0 0]
int32


In [67]:
z = np.zeros([2,3],dtype = int)
z

array([[0, 0, 0],
       [0, 0, 0]])

In [72]:
i = np.eye(5,dtype=int)
i

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [75]:
xyz = np.arange(0,10,2)
xyz

array([0, 2, 4, 6, 8])

# Creating a matrix using random values

In [80]:
ran_matrix = np.random.randint(1,10,size=(3,4))
ran_matrix.shape

(3, 4)

# Transpose of a matrix

In [82]:
ran_matrix_t = ran_matrix.T

In [83]:
ran_matrix_t.shape

(4, 3)

In [84]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [90]:
a = np.array([4,3,5,1,2])
print("Sum :",np.sum(a))
print("max :",np.max(a))
print("min :",np.min(a))
print("Index of Largest Value :",np.argmax(a))
print("Index of Smallest Value :",np.argmin(a))

Sum : 15
max : 5
min : 1
Index of Largest Value : 2
Index of Smallest Value : 3


In [95]:
from scipy import stats
a = np.array([4,3,5,2,1,2])
print("Mean: ",np.mean(a))
print("Median: ",np.median(a))
print("Range: ",np.ptp(a))
print("Mode: ",stats.mode(a))

Mean:  2.8333333333333335
Median:  2.5
Range:  4
Mode:  ModeResult(mode=array([2]), count=array([2]))


# Arithmetic operations and Broadcasting

In [1]:
import numpy as np
a = np.array([1,2])
b = np.array([3,4])

In [3]:
a.shape

(2,)

In [8]:
b.shape

(2,)

In [4]:
a+b

array([4, 6])

In [5]:
a*b

array([3, 8])

In [6]:
a-b

array([-2, -2])

In [7]:
a/b

array([0.33333333, 0.5       ])

In [9]:
a+2 #Broadcasting a scalar value to a vector

array([3, 4])

In [10]:
a*2

array([2, 4])

In [ ]:
#Point wise Operation

# Euclidean Distance

In [15]:
import numpy as np
a = np.array([1,2])
b = np.array([3,4])
d1 = np.linalg.norm(a)
d2 = np.linalg.norm(b)
print(d1,d2)
print(np.linalg.norm(a-b))

2.23606797749979 5.0
2.8284271247461903


In [27]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [28]:
print("Array after deleting column 0, axis = 1")
a = np.delete(a,0,axis=1)
print(a)
print(a.shape)

Array after deleting column 0, axis = 1
[[2 3]
 [5 6]
 [8 9]]
(3, 2)


In [29]:
print("Array after deleting row 2, axis = 0")
a = np.delete(a,2,axis=0)
print(a)
print(a.shape)

Array after deleting row 2, axis = 0
[[2 3]
 [5 6]]
(2, 2)


In [30]:
b = np.array([1,4])
print("Array after inserting column 0, axis = 1")
a = np.insert(a,0,b,axis=1)
print(a)
print(a.shape)

Array after inserting column 0, axis = 1
[[1 2 3]
 [4 5 6]]
(2, 3)


In [31]:
c = np.array([7,8,9])
print("Array after inserting row 0, axis = 0")
a = np.insert(a,2,c,axis=0)
print(a)
print(a.shape)

Array after inserting row 0, axis = 0
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


# Normalization using Min Max

In [36]:
x = np.array([1,2,3,4,5,6,7,8,9,10])

xmax = x.max()
print(xmax)
xmin = x.min()
print(xmin)

xnorm = (x-xmin)/(xmax-xmin)
print("Normalized Value ", xnorm)

10
1
Normalized Value  [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [52]:
a = np.array([1,2,3,4,5])
b = np.arange(5)
print(a,b)

[1 2 3 4 5] [0 1 2 3 4]


In [53]:
#csv - comma seperated values

In [55]:
np.savetxt('array_value.csv',(a,b),fmt = "%.2f")

In [57]:
xyz = open('array_value.csv').read()

In [58]:
print(xyz)

1.00 2.00 3.00 4.00 5.00
0.00 1.00 2.00 3.00 4.00

