# Whenever you import any library in python, it is treated as an object.

Object will have 2 components:
1. Method () - Functions 
2. Attribute  - Variables


Numpy's most important component is numpy array

# Importing numpy and printing its version


In [2]:
import numpy as np
print(np.__version__)

1.15.4


# Create a Numpy Array

In [117]:
a = np.array(12) # Method array()
print(a)
print(type(a))
print(id(a))
print(a.size) # Total size of an array
print(a.shape) # No of rows and colums
print(a.dtype) # Datat type of a variable
print(a.ndim ) #Dimension of an array

12
<class 'numpy.ndarray'>
1896415447840
1
()
int32
0


In [16]:
#Example 2

In [18]:
a = np.array([12.2]) # Method array()
print(a)
print(type(a))
print(a.size) # Total size of an array
print(a.shape) # No of rows and colums
print(a.dtype) # Datat type of a variable
print(a.ndim ) #Dimension of an array

[12.2]
<class 'numpy.ndarray'>
1
(1,)
float64
1


In [19]:
# Example 3

In [92]:
a = np.array([1,2,3,4,5]) # Method array()
print(a)
print(type(a))
print(a.size) # Total size of an array
print(a.shape) # No of rows and colums
print(a.dtype) # Datat type of a variable
print(a.ndim ) #Dimension of an array

[1 2 3 4 5]
<class 'numpy.ndarray'>
5
(5,)
int32
1


# Appending a value

In [93]:
a = np.append(a,6)
a

array([1, 2, 3, 4, 5, 6])

# Power and sqrt of a vector

In [73]:
np.power(a,2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [64]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [21]:
# Example 4

In [ ]:
#Scalar is a single value 2D
#Vector is a single row or column 1D
#Matrix is one or more rows, one or more columns 2D

In [59]:
a = np.array([[1,2,3],[4,5,6]]) # Method array()
print(a)
print(type(a))
print(a.size) # Total size of an array
print(a.shape) # No of rows and colums
print(a.dtype) # Datat type of a variable
print(a.ndim ) #Dimension of an array

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
6
(2, 3)
int32
2


In [23]:
# np.zeros

In [28]:
a  =np.zeros(10,dtype = int)
print(a)
print(a.dtype)

[0 0 0 0 0 0 0 0 0 0]
int32


In [29]:
a  =np.zeros([3,3],dtype = int)
print(a)
print(a.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
int32


In [30]:
a  =np.ones([3,3],dtype = int)
print(a)
print(a.dtype)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
int32


In [53]:
i = np.eye(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
c = np.arange(0,10,2)
c

array([0, 2, 4, 6, 8])

# Taking random value as a vector

In [119]:
d = np.random.randint(1,20,10)
d

array([16,  6, 11,  9,  9,  3,  2,  6,  7,  4])

# Reshaping an array

In [120]:
d.reshape(2,5)

array([[16,  6, 11,  9,  9],
       [ 3,  2,  6,  7,  4]])

In [121]:
d.reshape(2,5).astype('float32')

array([[16.,  6., 11.,  9.,  9.],
       [ 3.,  2.,  6.,  7.,  4.]], dtype=float32)

In [111]:
d.sort()
d

array([ 1,  2,  6,  6, 10, 13, 18, 18, 19, 19])

In [116]:
d = np.unique(d)
d

array([ 1,  2,  6, 10, 13, 18, 19])

# Arithmetic operations

In [40]:
print(d*2)  
print(d+2)

[ 2 20 26 38 38  4 36 12 12 36]
[ 3 12 15 21 21  4 20  8  8 20]


In [ ]:
abc = np.arange(5)
abc

In [ ]:
2*abc #point-wise operation

abc+1 #Broadcasting scalar value to a vector

abc+4

# Random Integer value Matrix

In [33]:
x = np.random.randint(1,10,size=(3,4))
x

array([[5, 8, 1, 4],
       [4, 8, 1, 9],
       [5, 5, 3, 1]])

In [34]:
#Tranpose of matrix

In [35]:
x.T

array([[5, 4, 5],
       [8, 8, 5],
       [1, 1, 3],
       [4, 9, 1]])

In [62]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [54]:
#Sum, Mean max on Vectors

In [74]:
a = np.array([4,5,3,1,2])
print(np.sum(a))
print(np.max(a))
print(np.min(a))
print(np.mean(a))
print(np.argmax(a))
print(np.argmin(a))

15
5
1
3.0
1
3


# Inserting and Deleting Values

In [47]:
print(" Printing orignal Array")
a  = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.shape)

 Printing orignal Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [48]:
print(" Array after deleting column, axis =1")
a = np.delete(a,0,axis =1)
print(a)
print(a.shape)

 Array after deleting column, axis =1
[[2 3]
 [5 6]
 [8 9]]
(3, 2)


In [49]:
print(" Array after deleting row, axis =0")
a = np.delete(a,0,axis =0)
print(a)
print(a.shape)

 Array after deleting row, axis =0
[[5 6]
 [8 9]]
(2, 2)


In [50]:
b = np.array([4,7])
print(" Array after inserting column , axis =1")
a = np.insert(a,0,b,axis = 1)
print(a)
print(a.shape)

 Array after inserting column , axis =1
[[4 5 6]
 [7 8 9]]
(2, 3)


In [51]:
c = np.array([1,2,3])
print(" Array after inserting row , axis =0")
a = np.insert(a,0,c,axis = 0)
print(a)
print(a.shape)

 Array after inserting row , axis =0
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [52]:
#MAths

In [53]:
a = np.array([[1,2],[3,4]])

In [54]:
a

array([[1, 2],
       [3, 4]])

In [58]:
print(np.sum(a))
print(np.sum(a,axis=1))
print(np.sum(a,axis=0))

10
[3 7]
[4 6]


# Normalization of an array

Normalizing an array is the process of bringing the array values to some defined range. For example, we can say we want to normalize an array between -1 and 1 and so on.

The formula for normalization is as follows:

x = (x – xmin) / (xmax – xmin)
Now we will just apply this formula to our array to normalize it. To find the maximum and minimum items in the array, we will use the max() and min() methods of NumPy respectively.

In [94]:
import numpy as np

x= np.array([400, 800, 200, 700, 1000, 2000, 300])

xmax = x.max()

xmin = x.min()

x = (x - xmin)/(xmax - xmin)

print("After normalization array x = \n", x)

After normalization array x = 
 [0.11111111 0.33333333 0.         0.27777778 0.44444444 1.
 0.05555556]


# Saving File as a csv

In [106]:
a = np.array([1, 2, 3, 4, 5])

np.savetxt("myArray.csv", a,fmt='%.2f')

In [107]:
import csv
with open('myArray.csv', newline='') as csvfile:
    spamreader = csv.reader(csvfile, delimiter=' ', quotechar='|')
    for row in spamreader:
        print(', '.join(row))

1.00
2.00
3.00
4.00
5.00


In [108]:
open('myArray.csv').read()

'1.00\n2.00\n3.00\n4.00\n5.00\n'